# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnapsackTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=36)),
                ('status', models.CharField(default='CREATED', max_length=20)),
                ('solver_type', models.CharField(blank=True, max_length=30)),
                ('done', models.BooleanField(default=False)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_solve_start', models.DateTimeField(blank=True, null=True)),
                ('task_solve_end', models.DateTimeField(blank=True, null=True)),
                ('task_total_duration', models.DurationField(default=datetime.timedelta(0))),
                ('task_solution_duration', models.DurationField(default=datetime.timedelta(0))),
                ('exception_class', models.TextField(blank=True)),
                ('exception_msg', models.TextField(blank=True)),
                ('exception_traceback', models.TextField(blank=True)),
                ('input', jsonfield.fields.JSONField(default='{}')),
                ('capacity', models.FloatField(default=0.0)),
                ('nitems', models.IntegerField(default=0)),
                ('result_weight', models.FloatField(default=0.0)),
                ('result_value', models.FloatField(default=0.0)),
                ('result_items', jsonfield.fields.JSONField(default='{}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_of_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
