# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnapsackTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=36)),
                ('status', models.CharField(max_length=20)),
                ('solver_type', models.CharField(max_length=30)),
                ('done', models.BooleanField(default=False)),
                ('exception_class', models.TextField(blank=True)),
                ('exception_msg', models.TextField(blank=True)),
                ('exception_traceback', models.TextField(blank=True)),
                ('input', jsonfield.fields.JSONField(default='{}')),
                ('capacity', models.FloatField(default=0.0)),
                ('nitems', models.IntegerField(default=0)),
                ('result_weight', models.FloatField(default=0.0)),
                ('result_value', models.FloatField(default=0.0)),
                ('result_items', jsonfield.fields.JSONField(blank=True)),
            ],
        ),
    ]
